version: "3.8"

services:
  workspace:
    container_name: ${PROJECT_NAME}-workspace
    build:
        context: ./workspace
        dockerfile: ./docker/workspace/Dockerfile
    ports:
        - ${VITE_PORT}:8000
    expose:
        - 9000
    volumes:
      - ../:/var/www/${PROJECT_NAME}:cached

  db:
    container_name: ${PROJECT_NAME}-db
    image: mysql:latest
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql:rw

  nginx:
    container_name: ${PROJECT_NAME}-nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ..:/var/www/${PROJECT_NAME}:rw
      - ../../logs/nginx/:/var/log/nginx
    depends_on:
      - workspace

volumes:
  db_data:
